### ISSUE TITLE
Who can we ask to read the report?

### ISSUE THREAD

**Issue by MarcusLowey** [futureplant/tourismdashboard#1]
Hello,

All of you did a very good work, congratulations! :)

Where it is possible to read the report please?

Have a nice day,
Marcus LOWEY

**Comment by futureplant** [comment]
Hello Marcus! 

Are you working with Fairbnb? 

Best regards,
Joey

**Comment by MarcusLowey** [comment]
Hello Joey,

I'm working with Oracle.

Best regards too,
